from windows.baseColors import bodyBGcolor, navigatorBGcolor, mouseHoverColor
from tkinter import PhotoImage, Button
from PIL import ImageTk

def createObjects(Button, root):
    photo=ImageTk.PhotoImage(file= "./images/valves/vert-oeste-valvula-def.png")

    boton = Button(root, border=0)
    boton.config(image=photo)
    boton.config(bg=bodyBGcolor())
    boton.place(x=60,y=100)

    return boton

def CreateNavigatorButtons(navigatorFrame, text, x, y=0, color="#686868", fontColor="white"):
    genericButton = Button(navigatorFrame, text=text, bg=color, fg=fontColor)
    genericButton.place(x=x,y=y)
    return genericButton

def changeOnHover(button, colorOnHover, colorOnLeave): 
    button.bind("<Enter>", func=lambda e: button.config(background=colorOnHover)) 
    button.bind("<Leave>", func=lambda e: button.config(background=colorOnLeave))

def CreateBodyButtons(bodyFrame, objType, x, y, image, color="#686868"):
    genericButton = objType(bodyFrame, border=0, image=image, bg=color)
    genericButton.place(x=x,y=y)
    changeOnHover(genericButton, "white", color)
    return genericButton

def importImages():
    listImages = {}
    #--------------------BALANÇAS----------------------
    listImages['balanca_interlok_g'] = PhotoImage(file="./images/balance/balanca-interlok-g.png")
    listImages['balanca_interlok_m'] = PhotoImage(file="./images/balance/balanca-interlok-m.png")
    listImages['balanca_interlok_p'] = PhotoImage(file="./images/balance/balanca-interlok-p.png")
    listImages['balanca_ausent_g'] = PhotoImage(file="./images/balance/balanca-ausent-g.png")
    listImages['balanca_ausent_m'] = PhotoImage(file="./images/balance/balanca-ausent-m.png")
    listImages['balanca_ausent_p'] = PhotoImage(file="./images/balance/balanca-ausent-p.png")
    listImages['balanca_fail_g'] = PhotoImage(file="./images/balance/balanca-fail-g.png")
    listImages['balanca_fail_m'] = PhotoImage(file="./images/balance/balanca-fail-m.png")
    listImages['balanca_fail_p'] = PhotoImage(file="./images/balance/balanca-fail-p.png")
    listImages['balanca_ppp_g'] = PhotoImage(file="./images/balance/balanca-ppp-g.png")
    listImages['balanca_ppp_m'] = PhotoImage(file="./images/balance/balanca-ppp-m.png")
    listImages['balanca_ppp_p'] = PhotoImage(file="./images/balance/balanca-ppp-p.png")
    listImages['balanca_run_g'] = PhotoImage(file="./images/balance/balanca-run-g.png")
    listImages['balanca_run_m'] = PhotoImage(file="./images/balance/balanca-run-m.png")
    listImages['balanca_run_p'] = PhotoImage(file="./images/balance/balanca-run-p.png")
    listImages['balanca_def_g'] = PhotoImage(file="./images/balance/balanca-def-g.png")
    listImages['balanca_def_m'] = PhotoImage(file="./images/balance/balanca-def-m.png")
    listImages['balanca_def_p'] = PhotoImage(file="./images/balance/balanca-def-p.png")
    #--------------------AQUECEDORES----------------------
    listImages['aquecedor_interlok_g'] = PhotoImage(file="./images/heater/aquecedor-interlok-g.png")
    listImages['aquecedor_interlok_m'] = PhotoImage(file="./images/heater/aquecedor-interlok-m.png")
    listImages['aquecedor_interlok_p'] = PhotoImage(file="./images/heater/aquecedor-interlok-p.png")
    listImages['aquecedor_ausent_g'] = PhotoImage(file="./images/heater/aquecedor-ausent-g.png")
    listImages['aquecedor_ausent_p'] = PhotoImage(file="./images/heater/aquecedor-ausent-p.png")
    listImages['aquecedor_ausent_m'] = PhotoImage(file="./images/heater/aquecedor-ausent-m.png")
    listImages['aquecedor_fail_g'] = PhotoImage(file="./images/heater/aquecedor-fail-g.png")
    listImages['aquecedor_fail_m'] = PhotoImage(file="./images/heater/aquecedor-fail-m.png")
    listImages['aquecedor_fail_p'] = PhotoImage(file="./images/heater/aquecedor-fail-p.png")
    listImages['aquecedor_ppp_g'] = PhotoImage(file="./images/heater/aquecedor-ppp-g.png")
    listImages['aquecedor_ppp_m'] = PhotoImage(file="./images/heater/aquecedor-ppp-m.png")
    listImages['aquecedor_ppp_p'] = PhotoImage(file="./images/heater/aquecedor-ppp-p.png")
    listImages['aquecedor_run_g'] = PhotoImage(file="./images/heater/aquecedor-run-g.png")
    listImages['aquecedor_run_m'] = PhotoImage(file="./images/heater/aquecedor-run-m.png")
    listImages['aquecedor_run_p'] = PhotoImage(file="./images/heater/aquecedor-run-p.png")
    listImages['aquecedor_def_g'] = PhotoImage(file="./images/heater/aquecedor-def-g.png")
    listImages['aquecedor_def_m'] = PhotoImage(file="./images/heater/aquecedor-def-m.png")
    listImages['aquecedor_def_p'] = PhotoImage(file="./images/heater/aquecedor-def-p.png")
    #--------------------MOTORES----------------------
    listImages['vert_norte_motor_interlok_g'] = PhotoImage(file="./images/motors/vert-norte-motor-interlok-g.png")
    listImages['vert_norte_motor_interlok_m'] = PhotoImage(file="./images/motors/vert-norte-motor-interlok-m.png")
    listImages['vert_norte_motor_interlok_p'] = PhotoImage(file="./images/motors/vert-norte-motor-interlok-p.png")
    listImages['vert_norte_motor_ausent_g'] = PhotoImage(file="./images/motors/vert-norte-motor-ausent-g.png")
    listImages['vert_norte_motor_ausent_m'] = PhotoImage(file="./images/motors/vert-norte-motor-ausent-m.png")
    listImages['vert_norte_motor_ausent_p'] = PhotoImage(file="./images/motors/vert-norte-motor-ausent-p.png")
    listImages['vert_norte_motor_fail_g'] = PhotoImage(file="./images/motors/vert-norte-motor-fail-g.png")
    listImages['vert_norte_motor_fail_m'] = PhotoImage(file="./images/motors/vert-norte-motor-fail-m.png")
    listImages['vert_norte_motor_fail_p'] = PhotoImage(file="./images/motors/vert-norte-motor-fail-p.png")
    listImages['vert_norte_motor_ppp_g'] = PhotoImage(file="./images/motors/vert-norte-motor-ppp-g.png")
    listImages['vert_norte_motor_ppp_m'] = PhotoImage(file="./images/motors/vert-norte-motor-ppp-m.png")
    listImages['vert_norte_motor_ppp_p'] = PhotoImage(file="./images/motors/vert-norte-motor-ppp-p.png")
    listImages['vert_norte_motor_run_g'] = PhotoImage(file="./images/motors/vert-norte-motor-run-g.png")
    listImages['vert_norte_motor_run_m'] = PhotoImage(file="./images/motors/vert-norte-motor-run-m.png")
    listImages['vert_norte_motor_run_p'] = PhotoImage(file="./images/motors/vert-norte-motor-run-p.png")
    listImages['vert_norte_motor_def_g'] = PhotoImage(file="./images/motors/vert-norte-motor-def-g.png")
    listImages['vert_norte_motor_def_m'] = PhotoImage(file="./images/motors/vert-norte-motor-def-m.png")
    listImages['vert_norte_motor_def_p'] = PhotoImage(file="./images/motors/vert-norte-motor-def-p.png")
    listImages['vert_sul_motor_interlok_g'] = PhotoImage(file="./images/motors/vert-sul-motor-interlok-g.png")
    listImages['vert_sul_motor_interlok_m'] = PhotoImage(file="./images/motors/vert-sul-motor-interlok-m.png")
    listImages['vert_sul_motor_interlok_p'] = PhotoImage(file="./images/motors/vert-sul-motor-interlok-p.png")
    listImages['vert_sul_motor_ausent_g'] = PhotoImage(file="./images/motors/vert-sul-motor-ausent-g.png")
    listImages['vert_sul_motor_ausent_m'] = PhotoImage(file="./images/motors/vert-sul-motor-ausent-m.png")
    listImages['vert_sul_motor_ausent_p'] = PhotoImage(file="./images/motors/vert-sul-motor-ausent-p.png")
    listImages['vert_sul_motor_fail_g'] = PhotoImage(file="./images/motors/vert-sul-motor-fail-g.png")
    listImages['vert_sul_motor_fail_m'] = PhotoImage(file="./images/motors/vert-sul-motor-fail-m.png")
    listImages['vert_sul_motor_fail_p'] = PhotoImage(file="./images/motors/vert-sul-motor-fail-p.png")
    listImages['vert_sul_motor_ppp_g'] = PhotoImage(file="./images/motors/vert-sul-motor-ppp-g.png")
    listImages['vert_sul_motor_ppp_m'] = PhotoImage(file="./images/motors/vert-sul-motor-ppp-m.png")
    listImages['vert_sul_motor_ppp_p'] = PhotoImage(file="./images/motors/vert-sul-motor-ppp-p.png")
    listImages['vert_sul_motor_run_g'] = PhotoImage(file="./images/motors/vert-sul-motor-run-g.png")
    listImages['vert_sul_motor_run_m'] = PhotoImage(file="./images/motors/vert-sul-motor-run-m.png")
    listImages['vert_sul_motor_run_p'] = PhotoImage(file="./images/motors/vert-sul-motor-run-p.png")
    listImages['vert_sul_motor_def_g'] = PhotoImage(file="./images/motors/vert-sul-motor-def-g.png")
    listImages['vert_sul_motor_def_m'] = PhotoImage(file="./images/motors/vert-sul-motor-def-m.png")
    listImages['vert_sul_motor_def_p'] = PhotoImage(file="./images/motors/vert-sul-motor-def-p.png")
    listImages['horz_leste_motor_interlok_g'] = PhotoImage(file="./images/motors/horz-leste-motor-interlok-g.png")
    listImages['horz_leste_motor_interlok_m'] = PhotoImage(file="./images/motors/horz-leste-motor-interlok-m.png")
    listImages['horz_leste_motor_interlok_p'] = PhotoImage(file="./images/motors/horz-leste-motor-interlok-p.png")
    listImages['horz_leste_motor_ausent_g'] = PhotoImage(file="./images/motors/horz-leste-motor-ausent-g.png")
    listImages['horz_leste_motor_ausent_m'] = PhotoImage(file="./images/motors/horz-leste-motor-ausent-m.png")
    listImages['horz_leste_motor_ausent_p'] = PhotoImage(file="./images/motors/horz-leste-motor-ausent-p.png")
    listImages['horz_leste_motor_fail_g'] = PhotoImage(file="./images/motors/horz-leste-motor-fail-g.png")
    listImages['horz_leste_motor_fail_m'] = PhotoImage(file="./images/motors/horz-leste-motor-fail-m.png")
    listImages['horz_leste_motor_fail_p'] = PhotoImage(file="./images/motors/horz-leste-motor-fail-p.png")
    listImages['horz_leste_motor_ppp_g'] = PhotoImage(file="./images/motors/horz-leste-motor-ppp-g.png")
    listImages['horz_leste_motor_ppp_m'] = PhotoImage(file="./images/motors/horz-leste-motor-ppp-m.png")
    listImages['horz_leste_motor_ppp_p'] = PhotoImage(file="./images/motors/horz-leste-motor-ppp-p.png")
    listImages['horz_leste_motor_run_g'] = PhotoImage(file="./images/motors/horz-leste-motor-run-g.png")
    listImages['horz_leste_motor_run_m'] = PhotoImage(file="./images/motors/horz-leste-motor-run-m.png")
    listImages['horz_leste_motor_run_p'] = PhotoImage(file="./images/motors/horz-leste-motor-run-p.png")
    listImages['horz_leste_motor_def_g'] = PhotoImage(file="./images/motors/horz-leste-motor-def-g.png")
    listImages['horz_leste_motor_def_m'] = PhotoImage(file="./images/motors/horz-leste-motor-def-m.png")
    listImages['horz_leste_motor_def_p'] = PhotoImage(file="./images/motors/horz-leste-motor-def-p.png")
    listImages['horz_oeste_motor_interlok_g'] = PhotoImage(file="./images/motors/horz-oeste-motor-interlok-g.png")
    listImages['horz_oeste_motor_interlok_m'] = PhotoImage(file="./images/motors/horz-oeste-motor-interlok-m.png")
    listImages['horz_oeste_motor_interlok_p'] = PhotoImage(file="./images/motors/horz-oeste-motor-interlok-p.png")
    listImages['horz_oeste_motor_ausent_g'] = PhotoImage(file="./images/motors/horz-oeste-motor-ausent-g.png")
    listImages['horz_oeste_motor_ausent_m'] = PhotoImage(file="./images/motors/horz-oeste-motor-ausent-m.png")
    listImages['horz_oeste_motor_ausent_p'] = PhotoImage(file="./images/motors/horz-oeste-motor-ausent-p.png")
    listImages['horz_oeste_motor_fail_g'] = PhotoImage(file="./images/motors/horz-oeste-motor-fail-g.png")
    listImages['horz_oeste_motor_fail_m'] = PhotoImage(file="./images/motors/horz-oeste-motor-fail-m.png")
    listImages['horz_oeste_motor_fail_p'] = PhotoImage(file="./images/motors/horz-oeste-motor-fail-p.png")
    listImages['horz_oeste_motor_ppp_g'] = PhotoImage(file="./images/motors/horz-oeste-motor-ppp-g.png")
    listImages['horz_oeste_motor_ppp_m'] = PhotoImage(file="./images/motors/horz-oeste-motor-ppp-m.png")
    listImages['horz_oeste_motor_ppp_p'] = PhotoImage(file="./images/motors/horz-oeste-motor-ppp-p.png")
    listImages['horz_oeste_motor_run_g'] = PhotoImage(file="./images/motors/horz-oeste-motor-run-g.png")
    listImages['horz_oeste_motor_run_m'] = PhotoImage(file="./images/motors/horz-oeste-motor-run-m.png")
    listImages['horz_oeste_motor_run_p'] = PhotoImage(file="./images/motors/horz-oeste-motor-run-p.png")
    listImages['horz_oeste_motor_def_g'] = PhotoImage(file="./images/motors/horz-oeste-motor-def-g.png")
    listImages['horz_oeste_motor_def_m'] = PhotoImage(file="./images/motors/horz-oeste-motor-def-m.png")
    listImages['horz_oeste_motor_def_p'] = PhotoImage(file="./images/motors/horz-oeste-motor-def-p.png")
    #--------------------VALVULAS----------------------
    listImages['horz_valvula_interlok_g'] = PhotoImage(file="./images/valves/horz-valvula-interlok-g.png")
    listImages['horz_valvula_interlok_m'] = PhotoImage(file="./images/valves/horz-valvula-interlok-m.png")
    listImages['horz_valvula_interlok_p'] = PhotoImage(file="./images/valves/horz-valvula-interlok-p.png")
    listImages['horz_valvula_ausent_g'] = PhotoImage(file="./images/valves/horz-valvula-ausent-g.png")
    listImages['horz_valvula_ausent_m'] = PhotoImage(file="./images/valves/horz-valvula-ausent-m.png")
    listImages['horz_valvula_ausent_p'] = PhotoImage(file="./images/valves/horz-valvula-ausent-p.png")
    listImages['horz_valvula_fail_g'] = PhotoImage(file="./images/valves/horz-valvula-fail-g.png")
    listImages['horz_valvula_fail_m'] = PhotoImage(file="./images/valves/horz-valvula-fail-m.png")
    listImages['horz_valvula_fail_p'] = PhotoImage(file="./images/valves/horz-valvula-fail-p.png")
    listImages['horz_valvula_ppp_g'] = PhotoImage(file="./images/valves/horz-valvula-ppp-g.png")
    listImages['horz_valvula_ppp_m'] = PhotoImage(file="./images/valves/horz-valvula-ppp-m.png")
    listImages['horz_valvula_ppp_p'] = PhotoImage(file="./images/valves/horz-valvula-ppp-p.png")
    listImages['horz_valvula_run_g'] = PhotoImage(file="./images/valves/horz-valvula-run-g.png")
    listImages['horz_valvula_run_m'] = PhotoImage(file="./images/valves/horz-valvula-run-m.png")
    listImages['horz_valvula_run_p'] = PhotoImage(file="./images/valves/horz-valvula-run-p.png")
    listImages['horz_valvula_def_g'] = PhotoImage(file="./images/valves/horz-valvula-def-g.png")
    listImages['horz_valvula_def_m'] = PhotoImage(file="./images/valves/horz-valvula-def-m.png")
    listImages['horz_valvula_def_p'] = PhotoImage(file="./images/valves/horz-valvula-def-p.png")
    listImages['vert_leste_valvula_interlok_g'] = PhotoImage(file="./images/valves/vert-leste-valvula-interlok-g.png")
    listImages['vert_leste_valvula_interlok_m'] = PhotoImage(file="./images/valves/vert-leste-valvula-interlok-m.png")
    listImages['vert_leste_valvula_interlok_p'] = PhotoImage(file="./images/valves/vert-leste-valvula-interlok-p.png")
    listImages['vert_leste_valvula_ausent_g'] = PhotoImage(file="./images/valves/vert-leste-valvula-ausent-g.png")
    listImages['vert_leste_valvula_ausent_m'] = PhotoImage(file="./images/valves/vert-leste-valvula-ausent-m.png")
    listImages['vert_leste_valvula_ausent_p'] = PhotoImage(file="./images/valves/vert-leste-valvula-ausent-p.png")
    listImages['vert_leste_valvula_fail_g'] = PhotoImage(file="./images/valves/vert-leste-valvula-fail-g.png")
    listImages['vert_leste_valvula_fail_m'] = PhotoImage(file="./images/valves/vert-leste-valvula-fail-m.png")
    listImages['vert_leste_valvula_fail_p'] = PhotoImage(file="./images/valves/vert-leste-valvula-fail-p.png")
    listImages['vert_leste_valvula_ppp_g'] = PhotoImage(file="./images/valves/vert-leste-valvula-ppp-g.png")
    listImages['vert_leste_valvula_ppp_m'] = PhotoImage(file="./images/valves/vert-leste-valvula-ppp-m.png")
    listImages['vert_leste_valvula_ppp_p'] = PhotoImage(file="./images/valves/vert-leste-valvula-ppp-p.png")
    listImages['vert_leste_valvula_run_g'] = PhotoImage(file="./images/valves/vert-leste-valvula-run-g.png")
    listImages['vert_leste_valvula_run_m'] = PhotoImage(file="./images/valves/vert-leste-valvula-run-m.png")
    listImages['vert_leste_valvula_run_p'] = PhotoImage(file="./images/valves/vert-leste-valvula-run-p.png")
    listImages['vert_leste_valvula_def_g'] = PhotoImage(file="./images/valves/vert-leste-valvula-def-g.png")
    listImages['vert_leste_valvula_def_m'] = PhotoImage(file="./images/valves/vert-leste-valvula-def-m.png")
    listImages['vert_leste_valvula_def_p'] = PhotoImage(file="./images/valves/vert-leste-valvula-def-p.png")
    listImages['vert_oeste_valvula_interlok_g'] = PhotoImage(file="./images/valves/vert-oeste-valvula-interlok-g.png")
    listImages['vert_oeste_valvula_interlok_m'] = PhotoImage(file="./images/valves/vert-oeste-valvula-interlok-m.png")
    listImages['vert_oeste_valvula_interlok_p'] = PhotoImage(file="./images/valves/vert-oeste-valvula-interlok-p.png")
    listImages['vert_oeste_valvula_ausent_g'] = PhotoImage(file="./images/valves/vert-oeste-valvula-ausent-g.png")
    listImages['vert_oeste_valvula_ausent_m'] = PhotoImage(file="./images/valves/vert-oeste-valvula-ausent-m.png")
    listImages['vert_oeste_valvula_ausent_p'] = PhotoImage(file="./images/valves/vert-oeste-valvula-ausent-p.png")
    listImages['vert_oeste_valvula_fail_g'] = PhotoImage(file="./images/valves/vert-oeste-valvula-fail-g.png")
    listImages['vert_oeste_valvula_fail_m'] = PhotoImage(file="./images/valves/vert-oeste-valvula-fail-m.png")
    listImages['vert_oeste_valvula_fail_p'] = PhotoImage(file="./images/valves/vert-oeste-valvula-fail-p.png")
    listImages['vert_oeste_valvula_ppp_g'] = PhotoImage(file="./images/valves/vert-oeste-valvula-ppp-g.png")
    listImages['vert_oeste_valvula_ppp_m'] = PhotoImage(file="./images/valves/vert-oeste-valvula-ppp-m.png")
    listImages['vert_oeste_valvula_ppp_p'] = PhotoImage(file="./images/valves/vert-oeste-valvula-ppp-p.png")
    listImages['vert_oeste_valvula_run_g'] = PhotoImage(file="./images/valves/vert-oeste-valvula-run-g.png")
    listImages['vert_oeste_valvula_run_m'] = PhotoImage(file="./images/valves/vert-oeste-valvula-run-m.png")
    listImages['vert_oeste_valvula_run_p'] = PhotoImage(file="./images/valves/vert-oeste-valvula-run-p.png")
    listImages['vert_oeste_valvula_def_g'] = PhotoImage(file="./images/valves/vert-oeste-valvula-def-g.png")
    listImages['vert_oeste_valvula_def_m'] = PhotoImage(file="./images/valves/vert-oeste-valvula-def-m.png")
    listImages['vert_oeste_valvula_def_p'] = PhotoImage(file="./images/valves/vert-oeste-valvula-def-p.png")
    #--------------------BOMBAS----------------------
    listImages['bomba_interlok_g'] = PhotoImage(file="./images/waterpump/bomba-interlok-g.png")
    listImages['bomba_interlok_m'] = PhotoImage(file="./images/waterpump/bomba-interlok-m.png")
    listImages['bomba_interlok_p'] = PhotoImage(file="./images/waterpump/bomba-interlok-p.png")
    listImages['bomba_ausent_g'] = PhotoImage(file="./images/waterpump/bomba-ausent-g.png")
    listImages['bomba_ausent_m'] = PhotoImage(file="./images/waterpump/bomba-ausent-m.png")
    listImages['bomba_ausent_p'] = PhotoImage(file="./images/waterpump/bomba-ausent-p.png")
    listImages['bomba_fail_g'] = PhotoImage(file="./images/waterpump/bomba-fail-g.png")
    listImages['bomba_fail_p'] = PhotoImage(file="./images/waterpump/bomba-fail-p.png")
    listImages['bomba_fail_m'] = PhotoImage(file="./images/waterpump/bomba-fail-m.png")
    listImages['bomba_ppp_g'] = PhotoImage(file="./images/waterpump/bomba-ppp-g.png")
    listImages['bomba_ppp_p'] = PhotoImage(file="./images/waterpump/bomba-ppp-p.png")
    listImages['bomba_ppp_m'] = PhotoImage(file="./images/waterpump/bomba-ppp-m.png")
    listImages['bomba_run_g'] = PhotoImage(file="./images/waterpump/bomba-run-g.png")
    listImages['bomba_run_p'] = PhotoImage(file="./images/waterpump/bomba-run-p.png")
    listImages['bomba_run_m'] = PhotoImage(file="./images/waterpump/bomba-run-m.png")
    listImages['bomba_def_g'] = PhotoImage(file="./images/waterpump/bomba-def-g.png")
    listImages['bomba_def_m'] = PhotoImage(file="./images/waterpump/bomba-def-m.png")
    listImages['bomba_def_p'] = PhotoImage(file="./images/waterpump/bomba-def-p.png")
    #--------------------SILO----------------------
    listImages['silo_0'] = PhotoImage(file="./images/silo/silo-0.png")
    listImages['silo_20'] = PhotoImage(file="./images/silo/silo-20.png")
    listImages['silo_40'] = PhotoImage(file="./images/silo/silo-40.png")
    listImages['silo_60'] = PhotoImage(file="./images/silo/silo-60.png")
    listImages['silo_80'] = PhotoImage(file="./images/silo/silo-80.png")
    listImages['silo_100'] = PhotoImage(file="./images/silo/silo-100.png")
    #--------------------MOINHO----------------------
    listImages['moinho_interlok_g'] = PhotoImage(file="./images/moinho/moinho-interlok-g.png")
    listImages['moinho_ausent_g'] = PhotoImage(file="./images/moinho/moinho-ausent-g.png")
    listImages['moinho_run_1_g'] = PhotoImage(file="./images/moinho/moinho-run-1-g.png")
    listImages['moinho_run_2_g'] = PhotoImage(file="./images/moinho/moinho-run-2-g.png")
    listImages['moinho_run_3_g'] = PhotoImage(file="./images/moinho/moinho-run-3-g.png")
    listImages['moinho_ppp_g'] = PhotoImage(file="./images/moinho/moinho-ppp-g.png")
    listImages['moinho_def_g'] = PhotoImage(file="./images/moinho/moinho-def-g.png")
    listImages['moinho_interlok_m'] = PhotoImage(file="./images/moinho/moinho-interlok-m.png")
    listImages['moinho_ausent_m'] = PhotoImage(file="./images/moinho/moinho-ausent-m.png")
    listImages['moinho_run_1_m'] = PhotoImage(file="./images/moinho/moinho-run-1-m.png")
    listImages['moinho_run_2_m'] = PhotoImage(file="./images/moinho/moinho-run-2-m.png")
    listImages['moinho_run_3_m'] = PhotoImage(file="./images/moinho/moinho-run-3-m.png")
    listImages['moinho_ppp_m'] = PhotoImage(file="./images/moinho/moinho-ppp-m.png")
    listImages['moinho_def_m'] = PhotoImage(file="./images/moinho/moinho-def-m.png")
    listImages['moinho_interlok_p'] = PhotoImage(file="./images/moinho/moinho-interlok-p.png")
    listImages['moinho_ausent_p'] = PhotoImage(file="./images/moinho/moinho-ausent-p.png")
    listImages['moinho_run_1_p'] = PhotoImage(file="./images/moinho/moinho-run-1-p.png")
    listImages['moinho_run_2_p'] = PhotoImage(file="./images/moinho/moinho-run-2-p.png")
    listImages['moinho_run_3_p'] = PhotoImage(file="./images/moinho/moinho-run-3-p.png")
    listImages['moinho_ppp_p'] = PhotoImage(file="./images/moinho/moinho-ppp-p.png")
    listImages['moinho_def_p'] = PhotoImage(file="./images/moinho/moinho-def-p.png")
    #--------------------TUBULACOES----------------------
    listImages['tubo_fim_leste_g'] = PhotoImage(file="./images/tubulacoes/tubo-fim-leste-g.png")
    listImages['tubo_fim_leste_p'] = PhotoImage(file="./images/tubulacoes/tubo-fim-leste-p.png")
    listImages['tubo_fim_norte_g'] = PhotoImage(file="./images/tubulacoes/tubo-fim-norte-g.png")
    listImages['tubo_fim_norte_p'] = PhotoImage(file="./images/tubulacoes/tubo-fim-norte-p.png")
    listImages['tubo_fim_oeste_g'] = PhotoImage(file="./images/tubulacoes/tubo-fim-oeste-g.png")
    listImages['tubo_fim_oeste_p'] = PhotoImage(file="./images/tubulacoes/tubo-fim-oeste-p.png")
    listImages['tubo_fim_sul_g'] = PhotoImage(file="./images/tubulacoes/tubo-fim-sul-g.png")
    listImages['tubo_fim_sul_p'] = PhotoImage(file="./images/tubulacoes/tubo-fim-sul-p.png")
    listImages['tubo_joelho_ls_g'] = PhotoImage(file="./images/tubulacoes/tubo-joelho-ls-g.png")
    listImages['tubo_joelho_ls_p'] = PhotoImage(file="./images/tubulacoes/tubo-joelho-ls-p.png")
    listImages['tubo_joelho_nl_g'] = PhotoImage(file="./images/tubulacoes/tubo-joelho-nl-g.png")
    listImages['tubo_joelho_nl_p'] = PhotoImage(file="./images/tubulacoes/tubo-joelho-nl-p.png")
    listImages['tubo_joelho_no_g'] = PhotoImage(file="./images/tubulacoes/tubo-joelho-no-g.png")
    listImages['tubo_joelho_no_p'] = PhotoImage(file="./images/tubulacoes/tubo-joelho-no-p.png")
    listImages['tubo_joelho_os_g'] = PhotoImage(file="./images/tubulacoes/tubo-joelho-os-g.png")
    listImages['tubo_joelho_os_p'] = PhotoImage(file="./images/tubulacoes/tubo-joelho-os-p.png")
    listImages['tubo_t_leste_g'] = PhotoImage(file="./images/tubulacoes/tubo-t-leste-g.png")
    listImages['tubo_t_leste_p'] = PhotoImage(file="./images/tubulacoes/tubo-t-leste-p.png")
    listImages['tubo_t_norte_g'] = PhotoImage(file="./images/tubulacoes/tubo-t-norte-g.png")
    listImages['tubo_t_norte_p'] = PhotoImage(file="./images/tubulacoes/tubo-t-norte-p.png")
    listImages['tubo_t_oeste_g'] = PhotoImage(file="./images/tubulacoes/tubo-t-oeste-g.png")
    listImages['tubo_t_oeste_p'] = PhotoImage(file="./images/tubulacoes/tubo-t-oeste-p.png")
    listImages['tubo_t_sul_g'] = PhotoImage(file="./images/tubulacoes/tubo-t-sul-g.png")
    listImages['tubo_t_sul_p'] = PhotoImage(file="./images/tubulacoes/tubo-t-sul-p.png")
    listImages['tubo_horz_g'] = PhotoImage(file="./images/tubulacoes/tubo-horz-g.png")
    listImages['tubo_horz_p'] = PhotoImage(file="./images/tubulacoes/tubo-horz-p.png")
    listImages['tubo_vert_g'] = PhotoImage(file="./images/tubulacoes/tubo-vert-g.png")
    listImages['tubo_vert_pp'] = PhotoImage(file="./images/tubulacoes/tubo-vert-pp.png")
    listImages['tubo_vert_p'] = PhotoImage(file="./images/tubulacoes/tubo-vert-p.png")
    #--------------------CORREIAS----------------------
    listImages['correia_interlok_p'] = PhotoImage(file="./images/correia/correia-interlok-p.png")
    listImages['correia_ausent_p'] = PhotoImage(file="./images/correia/correia-ausent-p.png")
    listImages['correia_run_3_p'] = PhotoImage(file="./images/correia/correia-run-3-p.png")
    listImages['correia_run_2_p'] = PhotoImage(file="./images/correia/correia-run-2-p.png")
    listImages['correia_run_1_p'] = PhotoImage(file="./images/correia/correia-run-1-p.png")
    listImages['correia_fail_p'] = PhotoImage(file="./images/correia/correia-fail-p.png")
    listImages['correia_ppp_p'] = PhotoImage(file="./images/correia/correia-ppp-p.png")
    listImages['correia_def_p'] = PhotoImage(file="./images/correia/correia-def-p.png")
    #--------------------TANQUES----------------------
    listImages['tanque_0_g'] = PhotoImage(file="./images/tanque/tanque-0-g.png")
    listImages['tanque_20_g'] = PhotoImage(file="./images/tanque/tanque-20-g.png")
    listImages['tanque_40_g'] = PhotoImage(file="./images/tanque/tanque-40-g.png")
    listImages['tanque_40_g'] = PhotoImage(file="./images/tanque/tanque-60-g.png")
    listImages['tanque_80_g'] = PhotoImage(file="./images/tanque/tanque-80-g.png")
    listImages['tanque_100_g'] = PhotoImage(file="./images/tanque/tanque-100-g.png")

    return listImages